- src/js/app.js
- src/js/config/router.js
- src/js/directive/contact.js
- src/js/directive/contacts.js
- src/js/directive/discussions.js
- src/js/directive/header.js
- src/js/directive/layout/application-wrapper.js
- src/js/directive/thread.js
- src/js/directive/thread/message.js
- src/js/directive/widget/contact/avatar-letter.js
- src/js/service/helper/contact-helper.js
+ add routes for contact list and show
> feat(design): add contact list

- src/js/directive/discussions.js
- src/js/directive/thread.js
use reselect to map directives with the state
> refactor(various): implement reselect

- src/js/app.js
- src/js/config/server.js
redirect to base url when a http request requires an authentication
> feat(various): authentication required

- src/js/action/action-types.js
- src/js/action/user.js
- src/js/app.js
- src/js/directive/header.js
- src/js/directive/layout/user-menu.js
- src/js/reducer/reducers.js
- src/js/reducer/user-reducer.js
- src/js/service/repository/user.js
imported from previous repo: caliopen/frontend
+ login information
+ logout link
> feat(various): add basic user menu

- package.json
angular does'nt follow semver.
this also fix peerDependencies from redux-ui-router
> chore(various): force minor version of angular

- src/js/reducer/tab-reducer.js
> fix(various): unable to close tab

- src/js/directive/layout/application-wrapper.js
Action button needs `ctrl.currentApplication`
> fix(various): add application state for action button

- src/assets/translations/en.json
- src/assets/translations/fr.json
- src/js/app.js
- src/js/directive/header.js
- src/js/directive/layout/search-field.js
- src/styles/base/_base.scss
- src/styles/base/_colors.scss
- src/styles/components/_avatar.scss
- src/styles/components/_list.scss
- src/styles/components/_search-field.scss
- src/styles/components/_text-field.scss
- src/styles/layout/_header.scss
- src/styles/main.scss
Add search field design :
- Search field directive & controller (empty)
- .co-search-field SCSS object
Other adds (dependencies) :
- "Search" translations
- .co-text-field SCSS object
- standard SCSS form width variables
Other changes (dependencies) :
- Improve color palette
Previews :
> feat(design): add search field design

- src/js/directive/layout/application-switcher.js
> feat(design): use an inline menu instead of a dropdown

- .travis.yml
- README.md
- gulpfile.js
- package.json
Changes:
- Add travis config file
- Add dependencies version check (gulp and npm)
- Update README.md
:warning: Require:
> chore(build): add travis and dependencies check

- gulpfile.js
Fix gulp-plumber which prevent the container to crash, but stop the file watching
> fix(build): fix gulp plumber

- src/assets/translations/en.json
- src/assets/translations/fr.json
- src/js/directive/contact.js
- src/styles/component/_avatar.scss
- src/styles/component/_tag.scss
- src/styles/component/_text-list.scss
- src/styles/main.scss
- src/styles/page/_contact.scss
Add single contact page.
**Other changes**:
- Add tag (`.co-tag`) and list (`.co-text-list`) components
- Make `.co-avatar` modifiers extendable
- Add required en/fr translations
**Previews**:
> feat(contact): add contact page

- gulpfile.js
- package.json
- src/index.html
- src/js/app.js
- src/js/config/loading-bar.js
+ add gulp task concat vendor's css
+ add a css vendor file
> feat(design): add general loading bar

- CONTRIBUTING.md
- src/js/app.js
- src/js/directive/discussions/thread.js
- src/js/directive/layout/tab-list.js
- src/js/filter/thread-contacts.js
- src/js/middleware/tab-middleware.js
- test/functional/features/10_discussion-spec.js
- test/unit/directive/discussions/thread-spec.js
- test/unit/filter/thread-contacts-spec.js
+ add threadContacts filter
+ render contacts on thread list
+ render contacts on tabs
cf. CaliOpen/Caliopen#3
> feat(thread): identify conversation by contact names

- src/index.html
- test/functional/index.html
+ add missing vendors.css in test/index.html
> fix(design): topbar closed sometimes on large screen

- src/styles/module/_m-search-field.scss
- src/styles/module/_m-text-field.scss
- src/styles/vendor/foundation-sites.scss
- src/styles/vendor/foundation-sites/_config.scss
**visual:**
* higher background on field focus
**config:**
* configure default foundation form field
**doc:**
* remove comented defaults for modified values
* link to latest foundation default config
> refactor(design): include foundation-forms

- src/styles/config/theme/dark.scss
- src/styles/module/_m-panel.scss
- src/styles/module/_m-text-field.scss
Factorize "light" colors from
- `m-panel`
- `m-text-field`
under "contrasted foreground" colors (`$co-color__contrast`)
> refactor(design): factorize colors

- src/js/component/section/discussions/thread.js
- src/styles/module/_m-badge.scss
- src/styles/section/_s-thread-list.scss
+ design badges as in UI reference
+ add BEM modifier m-badge--low
fix caliopen/caliopen#4
> refactor(discussions): remove read count

- src/js/component/section/discussions/thread.js
- src/js/component/section/thread/message.js
- src/styles/section/_s-message.scss
- src/styles/section/_s-thread-list.scss
those are related to user settings
fix: https://trello.com/c/PUbUmuVU/209-supprimer-les-niveaux-d-importance-et-confidentialite-c-est-inherent-aux-double-sliders-amha
> refactor(discussion): remove importance & privacy indexes

- src/js/app.js
- src/js/component/layout/application-wrapper.js
- src/js/component/layout/navigation-alt.js
- src/js/component/layout/navigation-alt/tab-list.js
- src/js/component/module/tab-list.js
- src/styles/module/_m-tab.scss
- test/unit/component/module/tab-list-spec.js
+ refactor tab controller in module directory
> refactor(various): move tabs in navigation alt for small devices

- src/js/component/section/discussions/contacts-icon.js
when contacts from a thread start with same letter an error happens
> fix(thread): thread icon not displayed

- .eslintrc
- package.json
allow syntax like `{ ...object }` or `[...array]`
> chore(build): enable ES6 feature, spread operator

- src/js/component/section/contact-list/contact.js
TODO: the list needs to be fully refactored
cf. caliopen/caliopen#28
> fix(contact): remove info since it is not always displayed

- src/js/component/section/contact.js
- src/js/service/repository/contact.js
- src/styles/main.scss
- src/styles/module/_m-postal-address.scss
- test/functional/app_test.js
- test/functional/features/20_contact-spec.js
+ fix postal address rendering
+ support id in contactDetails
+ remove address in raw json from contact page
> refactor(various): update api

- src/js/app.js
- src/js/component/layout/application-wrapper.js
- src/js/component/layout/navigation/application-switcher.js
- src/js/component/layout/navigation/tab-list.js
- src/js/component/module/tab-list.js
- src/js/directive/horizontal-scroll.js
- src/styles/layout/_l-navbar.scss
- src/styles/main.scss
- src/styles/module/_m-application-switcher.scss
- src/styles/module/_m-horizontal-scroll.scss
- src/styles/module/_m-navbar.scss
- src/styles/module/_m-tab.scss
- test/functional/features/10_discussion-spec.js
- test/functional/features/30_tab-spec.js
- test/functional/utils/switch-application.js
missing features that requires refactors:
+ remember tabs position
+ hide anchors when useless
> feat(design): one line tabs with anchors

- src/js/component/layout/call-to-action.js
+ fix principal action selection
> fix(various): replate new contact icon

- src/js/common/navigation/index.js
- src/js/common/navigation/navigation.component.js
- src/js/common/navigation/sticky-navbar-class.directive.js
- src/styles/config/_config.scss
- src/styles/layout/_l-header.scss
- src/styles/layout/_l-navbar.scss
- src/styles/module/_m-avatar.scss
> feat(design): set navbar sticky

- src/js/common/infinite-scroll/index.js
- src/js/common/infinite-scroll/infinite-scroll.directive.js
- src/js/common/navigation/sticky-navbar-class.directive.js
- src/js/component/contact-list/contact-list.component.js
- src/js/component/contact-list/index.js
- src/js/component/discussions/discussions.component.js
- src/js/component/discussions/index.js
- src/styles/module/_m-application-switcher.scss
+ add infinite-scroll common module/directive
> feat(various): add infinite scroll on threads and contacts

- src/js/common/spinner/index.js
- src/js/common/spinner/spinner.component.js
- src/js/component/contact-card/contact-card.component.js
- src/js/component/contact-card/index.js
- src/js/component/contact-list/contact-list.component.js
- src/js/component/contact-list/index.js
- src/js/component/discussions/discussions.component.js
- src/js/component/discussions/index.js
- src/js/component/thread/index.js
- src/js/component/thread/thread.component.js
add spinner where data should appear
technicial:
refactor spinner into a common module component
> fix(design): add missing spinner

- src/js/common/dropdown/dropdown.component.js
- src/js/common/dropdown/index.js
- src/js/common/recipient-list/index.js
- src/js/common/recipient-list/recipient-list.component.js
- src/styles/module/_m-recipient-list.scss
+ add component dropdown: no dependency (except $document)
> fix(thread): click to select known contact on message redaction

- test/functional/protractor.conf.js
+ fix branch in saucelabs job name
+ add browsers : IE and safari
> chore(test): add multiCapabilities browsers for functional tests
